//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : database
	/// Data Source    : database
	/// Server Version : 3.24.0
	
	public partial class DatabaseDB : LinqToDB.Data.DataConnection
	{
		public ITable<TestInfo> TestInfos { get { return this.GetTable<TestInfo>(); } }

		public DatabaseDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DatabaseDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table("TestInfos")]
	public partial class TestInfo
	{
		[PrimaryKey, Identity] public long     Id       { get; set; } // integer
		[Column,     NotNull ] public string   TestName { get; set; } // varchar(1024)
		[Column,     NotNull ] public string   Operator { get; set; } // varchar(1024)
		[Column,     NotNull ] public string   Comment  { get; set; } // varchar(1024)
		[Column,     NotNull ] public DateTime Time     { get; set; } // datetime
	}

	public static partial class TableExtensions
	{
		public static TestInfo Find(this ITable<TestInfo> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}

#pragma warning restore 1591
