//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcess.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataProcess.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 纬度
        ///经度
        ///海拔高度
        ///东向速度
        ///北向速度
        ///Wx角速度
        ///Wy角速度
        ///Wz角速度
        ///轴向比力
        ///GNSS时间
        ///当前发射系X
        ///当前发射系Y
        ///当前发射系Z
        ///预示落点射程
        ///预示落点Z
        ///飞行总时间
        ///参试状态
        ///策略阶段
        ///策略判决结果1：总飞行时间
        ///策略判决结果1：侧向
        ///策略判决结果1：Wx角速度
        ///策略判决结果1：Wy角速度
        ///策略判决结果1：Wz角速度
        ///策略判决结果1：后向
        ///策略判决结果1：坠落
        ///策略判决结果1：分离时间
        ///策略判决结果2: 控制区下限
        ///策略判决结果2:控制区上限
        ///策略判决结果2:解保
        ///策略判决结果2:起爆
        ///策略判决结果2:模拟解保
        ///策略判决结果2:模拟起爆
        ///输入采集1：解保时序1状态
        ///输入采集1：解保时序2状态
        ///输入采集1：起爆控制状态
        ///输入采集1：解保控制状态
        ///输入采集1：火工品配电自保持状态
        ///输入采集1：紧急断电状态
        ///输入采集1：火工品BF配电指令状态
        ///输入采集1：起爆点火指令1状态
        ///输入采集2：起爆点火指令2状态
        ///输入采集2：解保指令1+状态
        ///输入采集2：解保指令1-状态
        ///输入采集2：解保指令2+状态
        ///输入采集2：解保指 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string 系统实时判决 {
            get {
                return ResourceManager.GetString("系统实时判决", resourceCulture);
            }
        }
    }
}
